opentok/opentok.py, setup.py, tests/__init__.py, tests/test_archive.py, tests/test_archive_api.py, tests/test_session_creation.py, tests/validate_jwt.py
I also changed the tests for the pre-existing X-TB-PARTNER-AUTH.
=> Implements JWT auth for REST API calls.

sample/Archiving/static/js/host.js, sample/Archiving/static/js/participant.js, sample/Archiving/templates/host.html, sample/Archiving/templates/participant.html, sample/HelloWorld/static/js/helloworld.js, sample/HelloWorld/templates/index.html
- Use latest JS API
- Use best practices and error handling
- Update URL for JS SDK
=> Update JS samples

opentok/opentok.py
Editing initial layout class docs.
=> Initial layout class docs edits

test_requirements.txt, tests/test_http_options.py
This picks up https://github.com/opentok/Opentok-Python-SDK/pull/57 which was meant to address https://github.com/opentok/Opentok-Python-SDK/issues/56 which was blocked for some time on an HTTPretty issue.
=> Default timeout

opentok/opentok.py, tests/test_http_options.py, tests/test_initialization.py
starts to address #56. the implementation probably works, but the testing is blocked on gabrielfalcao/HTTPretty#202
=> WIP add timeout option

opentok/opentok.py
=> Fixed wrong variable being used in create_session validation error message

README.rst, opentok/__init__.py, opentok/broadcast.py, opentok/endpoints.py, opentok/exceptions.py, opentok/opentok.py, opentok/version.py, tests/test_broadcast.py
The current `dev` branch is behind `master`, so this PR gives us a chance to check it to make sure this looks good, and if so, sync them back up
=> Moves the `dev` branch to match `master`

CODE_OF_CONDUCT.md, README.rst
Includes:
- Updated README.md to include branding change image
- Updated README.md to define additional support options
- Added CODE_OF_CONDUCT.md
=> Updating repo to adhere to Vonage repo-standards

.github/workflows/main.yml, .github/workflows/metrics.yml
Adding GitHub Action to record repository metrics to Firebase
=> Adding repo metric GitHub action

opentok/archives.py
=> Fix syntax warning over comparison of literals using is.

README.rst, setup.py
- Correcting malformed RST displaying on Pypi
=> Readme Format Changes

opentok/endpoints.py, opentok/opentok.py, test_requirements.txt, tests/test_opentok.py
Hi @dragonmantank I've added the new mute feature and would love your feedback on what I need to change/add or anything else! Thank you. Also, I have tests but will do a PR for those once the mute function is cleared for takeoff.
=> Adding version 1 of new function to mute all and specific streams

opentok/endpoints.py, opentok/opentok.py, test_requirements.txt, tests/test_opentok.py
=> Added mute/muteall functionality

.bumpversion.cfg, .github/workflows/ot.yml, opentok/__init__.py, opentok/archives.py, opentok/broadcast.py, opentok/endpoints.py, opentok/exceptions.py, opentok/opentok.py, opentok/version.py, test_requirements.txt, tests/test_archive.py, tests/test_archive_api.py, tests/test_broadcast.py
Hi, adding the first draft of the **Python Server SDK API implementation for selective stream (Archive/Broadcast**) for this ticket: [Jira Ticket](https://jira.vonage.com/browse/DEVX-5709)
=> Adding first draft of selective stream

CHANGES.md
- Adding changelog file `CHANGES.md`
- Incrementing version number to 3.2.0
=> Increment version 3.2.0

README.rst, opentok/archives.py, opentok/broadcast.py, opentok/exceptions.py, opentok/opentok.py, sample/Archiving/templates/base.html, setup.py, tests/test_broadcast.py, tests/test_custom_jwt_claims.py, tests/test_opentok.py
This replaces the PR from my fork of the repo, #205. Adds HLS options, documents previously undocumented methods, updates the insecure jQuery version the sample app was using, and includes some minor refactoring/cleaning up.
=> Add hls options and docs, fixing security vulnerability

README.rst, opentok/broadcast.py, opentok/opentok.py, tests/test_broadcast.py, tests/test_getter_setter.py, tests/test_initialization.py, tests/test_session_creation.py
- Adds a method allowing the user agent to be appended to
- Adds support for audio/video only broadcasts
- I will increment version number and changelog when the PR is approved and merged
=> Add append to user agent function, add audio/video only broadcasts

README.rst, opentok/opentok.py, tests/test_session_creation.py
Adds the new options `archive_name` and `archive_resolution` to the `create_session` method.
Also blackens the `opentok.py` file for consistency.
=> add auto archive improvements

.bumpversion.cfg, CHANGES.md, opentok/version.py
Prepares the SDK for a minor release
- version bump
- changelog update
=> V3.6.0 release

.bumpversion.cfg, CHANGES.md, opentok/endpoints.py, opentok/opentok.py, opentok/version.py, tests/test_archive.py, tests/test_broadcast.py
- Fixed broken `opentok.Client.add_archive_stream`, `opentok.Client.remove_archive_stream`, `opentok.Client.add_broadcast_stream` and `opentok.Client.remove_broadcast_stream` methods and tests
- Fixed `opentok.Endpoints.get_archive_stream` and `opentok.Endpoints.get_broadcast_stream` methods
- Blackened more of the code
- Prepared for a patch release
=> Fix streams methods

.bumpversion.cfg, CHANGES.md, opentok/opentok.py, opentok/version.py, tests/test_session_creation.py
- Fixed an issue with end-to-end encryption not being called correctly when creating a new session
=> Fix e2ee type

.bumpversion.cfg, CHANGES.md, README.rst, opentok/captions.py, opentok/endpoints.py, opentok/exceptions.py, opentok/opentok.py, opentok/version.py, tests/test_captions.py
Adds Captions API functionality to the SDK
Prepares the SDK for a minor release
=> Add captions api

.bumpversion.cfg, CHANGES.md, opentok/opentok.py, opentok/version.py, tests/test_token_generation.py
Add a publisher-only role to the list of valid roles
Prep for new release.
=> add publisher_only role for token generation
